### ISSUE TITLE
Update for Ubuntu 21.10

### ISSUE THREAD

**Issue by alpe12** [gerulrich/odroid-n2box#18]
Can you update it, please?
Latest Kodi version would be great too.
Thanks anyway.

**Comment by gerulrich** [comment]
Hi @alpe12
I can try but I don't promise anything.
I have compiled for Ubuntu 20.04 and have had some problems with Kodi Matrix, since the support for aml was removed, so it is necessary to put some coreelect patches.
On the other hand, even though I have compiled it for armhf, widevine is not working (kodi crash when trying to play content with widevine)

**Comment by alpe12** [comment]
> I can try but I don't promise anything.

No problem.

> On the other hand, even though I have compiled it for armhf, widevine is not working (kodi crash when trying to play content with widevine)

That's ok. I would mainly use IPTV.

Btw, do you know if it would be possible to make it run inside a docker container? Just curious about it. I've seen some containers mounting /tmp/.X11-unix/ to pass gui to the host.

**Comment by gerulrich** [comment]
> Btw, do you know if it would be possible to make it run inside a docker container? Just curious about it. I've seen some containers mounting /tmp/.X11-unix/ to pass gui to the host.

I think so. I have it pending to try (if it works i can make a step by step guide)

On the other hand, I have some issues for compile kodi 19.4 for ubuntu 21.10, but i keep trying (its working on ubuntu 18)

**Comment by gerulrich** [comment]
I was able to build kodi 19.4 for ubuntu 20.04 (with docker). The next step is to build for ubuntu 21.10

I have created the following Dockerfile:
```
FROM arm32v7/ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
        sudo jq build-essential git binutils gcc g++ \
        autopoint autoconf automake gettext \
        autotools-dev cmake curl default-jre devscripts \
        wget vim debhelper libasound2-dev
RUN useradd --create-home --shell /bin/bash odroid
RUN usermod -a -G sudo odroid
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER odroid
WORKDIR /home/odroid
CMD ["bash"]
```

**Build image**:

```
docker build -t ubuntu_focal --rm .
```

**Run**
```
docker run -it -d -v <path_to_local_folder>:/home/odroid --name compile --rm ubuntu_focal
docker exec -it compile bash
```

Before compiling, you need to install the dependencies. They can be installed with sudo apt-get install ... (without a password. If the container is restarted the packages need to be reinstalled)

Compile some packages (from this repo, libmali and libamcodec are required to compile kodi).
```
git clone https://github.com/gerulrich/odroid-n2box.git
cd odroid-n2box
./build -c -b -p libamcodec
./build -c -b -p libmali
```

once the libmali and libamcodec packages have been compiled, the image can be modified so that they are included in it:
Add this after apt-get install line:
```
COPY ./libamcodec-dev_0fbbe9fa6-1_all.deb  ./libamcodec_0fbbe9fa6-1_armhf.deb  ./libmali-dev_0.2-1_all.deb  ./libmali_0.2-1_armhf.deb ./
RUN dpkg -i libamcodec-dev_0fbbe9fa6-1_all.deb libamcodec_0fbbe9fa6-1_armhf.deb libmali-dev_0.2-1_all.deb libmali_0.2-1_armhf.deb
```

(I still have to push some commits)

**Comment by gerulrich** [comment]
Hi @alpe12 
I have been able to run kodi from a docker container successfully!
I have created a docker image to be able to run it:
```
docker run --name kodibuntu \
           --privileged \
           --cap-add=ALL -d \
           -v /home/odroid:/home/odroid \
           -v /dev:/dev \
           -v /lib/modules:/lib/modules \
           gerulrich/kodibuntu
```

Also I was able to compile kodi on ubuntu 21.10, in the next few days I will have the deb packages to upload.

**Comment by alpe12** [comment]
Awesome.
But --privileged and --cap-add=ALL are a big security concern.
I'll test it in a few days and see what caps can be dropped and a way to run without --privileged.

**Comment by gerulrich** [comment]
you can download the deb packages from here:

[Ubuntu 21.10 kodi repo](https://github.com/gerulrich/odroid-n2box/releases/tag/v19.4-impish-rc1)

Let me know if there is any problem.

**Comment by alpe12** [comment]
@gerulrich 
I'm testing it now.
Trying to make a docker image with less permissions.
Can you post the Dockerfile you used?
Also on [Ubuntu 21.10 kodi repo](https://github.com/gerulrich/odroid-n2box/releases/tag/v19.4-impish-rc1) there is no libamcodec for armhf (or all), only arm64. And no libmali for arm64, only armhf.
Thanks.

**Comment by gulrich1** [comment]
> Also on [Ubuntu 21.10 kodi repo](https://github.com/gerulrich/odroid-n2box/releases/tag/v19.4-impish-rc1) there is no libamcodec for armhf (or all), only arm64. And no libmali for arm64, only armhf.

I'm going to upload another tar.gz file with correct version of libamcodec. libmali for arm64 is provided by hardkernel in mali-fbdev package (because kodi is compiled for armhf it is not necessary arm64 dependencies. I only include the armhf.)

This is the docker file:

```
FROM arm32v7/ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
	libasound2 \
	libass9 \
	libbluetooth3 \
	libc6 \
	libcap2 \
	libcec4 \
	libcurl4 \
	libdbus-1-3 \
	libfreetype6 \
	libfribidi0 \
	libgcc-s1 \
	libgif7 \
	libgnutls30 \
	libinput10 \
	libjpeg8 \
	liblirc-client0 \
	liblzo2-2 \
	libmicrohttpd12 \
	libpcre3 \
	libpcrecpp0v5 \
	libpng16-16 \
	libpulse0 \
	libpython3.8 \
	libsqlite3-0 \
	libssl1.1 \
	libstdc++6 \
	libtag1v5 \
	libtinyxml2.6.2v5 \
	libudev1 \
	libuuid1 \
	libxkbcommon0 \
	libxml2 \
	libxslt1.1 \
	zlib1g \
	udisks2 \
	libc6 \
	libgcc-s1 \
	libstdc++6

COPY ./libamcodec-dev_0fbbe9fa6-1_all.deb  ./libamcodec_0fbbe9fa6-1_armhf.deb  ./libmali-dev_0.2-1_all.deb  ./libmali_0.2-1_armhf.deb ./kodi-bin_19.4-1~focal_armhf.deb ./kodi-data_19.4-1~focal_all.deb ./kodi_19.4-1~focal_armhf.deb ./
RUN dpkg -i libamcodec-dev_0fbbe9fa6-1_all.deb libamcodec_0fbbe9fa6-1_armhf.deb libmali-dev_0.2-1_all.deb libmali_0.2-1_armhf.deb kodi-bin_19.4-1~focal_armhf.deb kodi-data_19.4-1~focal_all.deb kodi_19.4-1~focal_armhf.deb
RUN useradd --create-home --shell /bin/bash odroid
RUN usermod -a -G cdrom,audio,video,plugdev,users,dialout,dip,input,sudo odroid
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER odroid
WORKDIR /home/odroid
CMD ["/usr/bin/kodi-standalone"]
```
